import{a as v,i as p,S as b}from"./assets/vendor-D0cagnvz.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const h=(o,t)=>{const s={params:{key:"21607463-49e6315ec3819cd7ca780513d",q:o,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:"true"}};return v.get("https://pixabay.com/api/",s)},f=o=>o.map(({webformatURL:t,largeImageURL:s,tags:c,likes:e,views:r,comments:a,downloads:L})=>`<a href="${s}" class="gallery-item">
  <div class="photo-card">
  <img src="${t}" alt="${c}" loading="lazy" width="360" />
  <div class="photo-info">
    <p class="photo-info-item">Likes<span>${e}</span></p>
	<p class="photo-info-item">Views<span>${r}</span></p>
	<p class="photo-info-item">Comments<span>${a}</span></p>
	<p class="photo-info-item">Downloads<span>${L}</span></p>
  </div>
  </div>
  </a>`).join(""),y=document.querySelector(".form-search"),u=document.querySelector(".gallery"),l=document.querySelector(".loader"),i=document.querySelector(".load-more-btn");let n=1,d="",m;i.classList.add("is-hidden");l.style.display="none";const q=async o=>{try{if(o.preventDefault(),u.innerHTML="",l.style.display="block",d=o.currentTarget.elements.user_query.value.trim(),d===""){p.warning({title:"Warning",position:"topRight",message:"Please enter a search query!"});return}n=1,i.classList.add("is-hidden");const{data:t}=await h(d,n);if(l.style.display="none",!t.hits.length){p.error({title:"Error",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}const s=f(t.hits);u.insertAdjacentHTML("beforeend",s),m=new b(".gallery-item",{captions:!0,captionsData:"alt",captionDelay:250}),m.refresh(),y.reset(),t.totalHits>1&&(i.classList.remove("is-hidden"),i.addEventListener("click",g))}catch{l.style.display="none"}};y.addEventListener("submit",q);const g=async o=>{try{n++;const{data:t}=await h(d,n),s=f(t.hits);u.insertAdjacentHTML("beforeend",s),m.refresh(),n*15>=t.totalHits&&(p.info({title:"Info",position:"topRight",message:"We're sorry, but you've reached the end of search results."}),i.classList.add("is-hidden"),i.removeEventListener("click",g)),w()}catch{p.error({title:"Error",position:"topRight",message:"Failed to load images. Please try again later."})}},w=()=>{const{height:o}=u.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
