import{a as L,S as b,i as l}from"./assets/vendor-D0cagnvz.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&d(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const m=(o,e)=>{const s={params:{key:"21607463-49e6315ec3819cd7ca780513d",q:o,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:"true"}};return L.get("https://pixabay.com/api/",s)},h=o=>o.map(({webformatURL:e,largeImageURL:s,tags:d,likes:t,views:r,comments:a,downloads:f})=>`<a href="${s}" class="gallery-item">
  <div class="photo-card">
  <img src="${e}" alt="${d}" loading="lazy" width="360" />
  <div class="photo-info">
    <p class="photo-info-item">Likes<span>${t}</span></p>
	<p class="photo-info-item">Views<span>${r}</span></p>
	<p class="photo-info-item">Comments<span>${a}</span></p>
	<p class="photo-info-item">Downloads<span>${f}</span></p>
  </div>
  </div>
  </a>`).join(""),g=document.querySelector(".form-search"),u=document.querySelector(".gallery"),n=document.querySelector(".loader"),i=document.querySelector(".load-more-btn");let c=1,p="",y=new b(".gallery-item",{captions:!0,captionsData:"alt",captionDelay:250});i.classList.add("is-hidden");n.style.display="none";const v=async o=>{try{if(o.preventDefault(),u.innerHTML="",n.style.display="block",p=o.currentTarget.elements.user_query.value.trim(),p===""){n.style.display="none",i.classList.add("is-hidden"),l.warning({title:"Warning",position:"topRight",message:"Please enter a search query!"});return}c=1,i.classList.add("is-hidden");const{data:e}=await m(p,c);if(n.style.display="none",!e.hits.length){l.error({title:"Error",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}const s=h(e.hits);u.insertAdjacentHTML("beforeend",s),y.refresh(),g.reset(),e.totalHits>15&&i.classList.remove("is-hidden")}catch(e){n.style.display="none",l.error({message:"Something went wrong, please try again later.",position:"topRight"}),console.error("Error fetching data:",e)}},w=async o=>{try{c++;const{data:e}=await m(p,c),s=h(e.hits);u.insertAdjacentHTML("beforeend",s),y.refresh(),c*15>=e.totalHits&&(l.info({title:"Info",position:"topRight",message:"We're sorry, but you've reached the end of search results."}),i.classList.add("is-hidden")),S()}catch{l.error({title:"Error",position:"topRight",message:"Failed to load images. Please try again later."})}},S=()=>{const o=document.querySelector(".gallery-item"),{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})};i.addEventListener("click",w);g.addEventListener("submit",v);
//# sourceMappingURL=index.js.map
